//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_baohanh
    {
        public int mactbh { get; set; }
        public Nullable<int> mactddh { get; set; }
        public Nullable<int> manv { get; set; }
        public Nullable<System.DateTime> ngaynhanmay { get; set; }
        public Nullable<System.DateTime> ngaytradukien { get; set; }
        public string soserial { get; set; }
        public Nullable<System.DateTime> ngaytrathucte { get; set; }
        public string tinhtrang { get; set; }
    
        public virtual ct_dondathang ct_dondathang { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
