//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_donhangnhap
    {
        public int mactdhn { get; set; }
        public Nullable<int> madhn { get; set; }
        public Nullable<int> mactsp { get; set; }
        public Nullable<long> giamua { get; set; }
        public Nullable<int> soluongmua { get; set; }
    
        public virtual ct_sanpham ct_sanpham { get; set; }
        public virtual donhangnhap donhangnhap { get; set; }
    }
}
