//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class fillter_thong_so
    {
        public int id { get; set; }
        public Nullable<int> matskt { get; set; }
        public Nullable<int> malts { get; set; }
    
        public virtual loaithongso loaithongso { get; set; }
        public virtual thongsokythuat thongsokythuat { get; set; }
    }
}
