//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_QLCHEntities2 : DbContext
    {
        public db_QLCHEntities2()
            : base("name=db_QLCHEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ct_baohanh> ct_baohanh { get; set; }
        public virtual DbSet<ct_dondathang> ct_dondathang { get; set; }
        public virtual DbSet<ct_donhangnhap> ct_donhangnhap { get; set; }
        public virtual DbSet<ct_sanpham> ct_sanpham { get; set; }
        public virtual DbSet<dondathang> dondathangs { get; set; }
        public virtual DbSet<donhangnhap> donhangnhaps { get; set; }
        public virtual DbSet<fillter_thong_so> fillter_thong_so { get; set; }
        public virtual DbSet<hang> hangs { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<loaihang> loaihangs { get; set; }
        public virtual DbSet<loaithongso> loaithongsoes { get; set; }
        public virtual DbSet<nhacungcap> nhacungcaps { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<thongsokythuat> thongsokythuats { get; set; }
    }
}
