//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.ct_baohanh = new HashSet<ct_baohanh>();
            this.dondathangs = new HashSet<dondathang>();
            this.donhangnhaps = new HashSet<donhangnhap>();
        }
    
        public int manv { get; set; }
        public string tennv { get; set; }
        public string giottinh { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
        public string cmnd { get; set; }
        public string passwword { get; set; }
        public Nullable<int> quyenhan { get; set; }
        public Nullable<int> trangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ct_baohanh> ct_baohanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dondathang> dondathangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donhangnhap> donhangnhaps { get; set; }
    }
}
