//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ct_sanpham()
        {
            this.ct_dondathang = new HashSet<ct_dondathang>();
            this.ct_donhangnhap = new HashSet<ct_donhangnhap>();
        }
    
        public int mactsp { get; set; }
        public Nullable<int> tinhtrang { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<int> masp { get; set; }
        public Nullable<long> giaban { get; set; }
        public Nullable<int> giasale { get; set; }
        public Nullable<System.DateTime> thoigianbh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ct_dondathang> ct_dondathang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ct_donhangnhap> ct_donhangnhap { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
