//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class dondathang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dondathang()
        {
            this.ct_dondathang = new HashSet<ct_dondathang>();
        }
    
        public int maddh { get; set; }
        public Nullable<int> manv { get; set; }
        public Nullable<int> makh { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
        public string trangthai { get; set; }
        public string ghichu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ct_dondathang> ct_dondathang { get; set; }
        public virtual khachhang khachhang { get; set; }
        public virtual nhanvien nhanvien { get; set; }
    }
}
